### ISSUE TITLE
Add @Mutable annotations to functional methods

### ISSUE THREAD

**Issue by Treiblesschorle** [scijava/scijava-ops#10]
Check that the functional methods of all functional interfaces defined by the new Ops system are correctly annotated with `@Mutable` annotations.

**Comment by ctrueden** [comment]
I double checked everything in `org.scijava.ops.core` at the moment, and all looks good.

Any reason to keep this open, @Treiblesschorle?

**Comment by Treiblesschorle** [comment]
Then it should be fine, I thought they are not yet there on the interfaces Gabe added.

**Comment by ctrueden** [comment]
Ah, you're right. I only checked the `new-ops` branch, not the WIP on `migrate-imagej-ops`. @gselzer Be sure to add this annotation to all the higher-order `Computer` interfaces!
