### ISSUE TITLE
OpTransformations should be done breadth-first, not depth-first

### ISSUE THREAD

**Issue by gselzer** [scijava/scijava-ops#18]
Currently, Op transformations are done on a depth-first basis. The logic is as follows
* Obtain all of the `OpTransformer`s that can transform into the desired Op Type
* For each returned transformer, check if there exists an Op that satisfies the parameters defined by the original Op.
  * If there exists no Op, transform your transformed Op yet again and check again for a satisfying Op
* If this original `OpTransformer` could not find an Op with its chain, try again with a different `OpTransformer`.

This can be problematic. For example, let's say that we want to use ops to run a `Function<Double, Double> addOp` using `ops.run()`. `ops.run()` will create an `OpRunner<Object> addOp`, will not be able to find a matching `OpRunner<Object> addOp` and then will run a transform. It would be nice if the matcher always settled on the
 `Function<Double, Object> -> OpRunner<Object>` 
transformer, but due to the fact that the matcher works on a depth first basis the transformation can become 
`Function<Double, Object> -> Computer<Double, Object> -> OpRunner<Object>`. This can be problematic, since then the `Function -> Computer` transformer will need to create an `Object` output to pass to the `Computer`. This will be an error more often than not.

Because of this it would be preferable to do a breadth-first search through the transformers, since it is usually (always?) desired to have the shortest transformation chain possible.

**Comment by ctrueden** [comment]
There is only one layer of adapting now, so this issue is moot.
