### ISSUE TITLE
OpService's prefix search does not work when parts of prefix are "empty"

### ISSUE THREAD

**Issue by MarcelWiedenmann** [scijava/scijava-ops#20]
Given `OpService ops` which contains the following entries in its cache (flat representation):
- math.add (OpInfo 1)
- math.add (OpInfo 2)
- math.sqrt (OpInfo 3)
- string.upper (OpInfo 4)

Calling `ops.infos("math")` should return OpInfos 1, 2, and 3. However, the call fails with "No op infos with name: math available.".
Adding an Op of name "math" to the cache resolves the problem: OpInfos 1, 2, 3, and the newly added OpInfo are returned. Thus, the problem seems to be caused by the namespace "math" being "empty" in the first scenario, that is, only containing further sub-namespaces, no actual Ops.

See [this gist](https://gist.github.com/MarcelWiedenmann/c088651dc6daa020f8f451190d39ee52) which reproduces the problem. It contains a copy of the relevant code parts of `OpService` as at 718bacb794f8ffe680fb50d2d64b59625b199f14, for the sake of portability,

Note that `PrefixTree.getAndBelow(PrefixQuery)` works correctly as far as I can tell. The faulty part should be the alias resolution in `OpService.infos(String)` (or alias registration during Op discovery).

It might be worth moving the cache-related functionality out of `OpService` and/or decouple the Op environment from its initialization (`OpService.initOpCache()`) to make it better unit testable. At the moment, writing isolated tests for the cache is somewhat complicated because it's always filled with all available Ops, that is, has a global scope/state.

**Comment by ctrueden** [comment]
> Calling `ops.infos("math")` should return OpInfos 1, 2, and 3. However, the call fails with "No op infos with name: math available.".

I thought you had to request ops by either fully qualified name (with namespace) or short name (no namespace). I do not think it is supposed to be possible to request _all ops of a given namespace_, is it?

**Comment by MarcelWiedenmann** [comment]
> I thought you had to request ops by either fully qualified name (with namespace) or short name (no namespace).

Yeah, I forgot about that option when we talked previously. But see below.

> I do not think it is supposed to be possible to request all ops of a given namespace, is it?

This _is_ already possible in some situations, however. In the above example that would be as soon as there's an Op with a fully qualified name of "math". `ops.infos("math")` will also then not only return an `OpInfo` for that particular Op but for all Ops in the "math" namespace: "math", "math.add", "math.add", "math.sqrt".

**Comment by gselzer** [comment]
I'll throw in my two cents here:
@MarcelWiedenmann: 
> In the above example that would be possible as soon as there's an Op with a fully qualified name of "math". ops.infos("math") will then return not only that particular Op but all Ops in the "math" namespace: "math", "math.add", "math.add", and "math.sqrt". I'm not sure if this is intended behavior or should be considered a bug.

I think that good practice is to give most if not all Ops a fully qualified name; I only see the argument for more "meta" Ops to be without one (looking at you `map`), although there really won't be many of these in the new iteration of Ops.

@ctrueden: 
> I do not think it is supposed to be possible to request all ops of a given namespace, is it? When would this be useful?

Outside of the `copy` scenario outlined by @MarcelWiedenmann, I can really only think of edge cases (pertaining mostly to those "meta" ops again) where you might want to do this. I am thinking of ops like `map`, where there is the subset  of `map.neighborhood` Ops. Maybe you want to use `map.neighborhood` and pass through a neighborhood but for whatever reason only look for a `map` Op? Although maybe this is a scenario we do not want to push, instead saying that if you want to map using a neighborhood you must ask for `map.neighborhood`, not just `map`.

However we probably should not let edge cases define the general code procedure. By and large asking for just a namespace does not even make sense. If you just ask for a `map` Op, you have no idea what you will be getting back, and I am not sure what the matcher will return when you have dozens of Ops, all with the same priority. Thus I would suggest that the user asks for a `math` Op, we only return Ops named `math` and no Ops named `math.add`, `math.sqrt`, etc.

I do, however, see the value in being able to compare all of the Ops in a namespace. I cannot think of any other valid scenarios outside of `copy` Ops (maybe `create` Ops too? I don't know...), however I see no reason for it to be impossible. I really see two ways of doing this:

1) Use aliases. Each `copy` Op is named `copy.______`, with the `copy` alias. I do not know if priority is given to the Ops with the shorter names (i.e. if we request a `copy` Op and we have a `copy` Op and a `copy.___` Op that both apply, we always return the `copy` Op), however I think this should probably apply (although I am not 100% convinced). This also requires that if someone implements another copy op they have to remember/know to add the `copy` alias.

2) Enable a `copy.*` syntax that would return all Ops that start with `copy` (`copy.`? Probably not...). This way the user **has to be intent on getting all copy Ops** to actually get all copy ops. Thus when a user looks for a `map` Op, they will only get standard `map` Ops, and the matcher will not even consider the `map.neighborhood` Ops. If the user really wants to look at both, then they can ask for a `map.*` Op, which might be `map` or `map.neighborhood` depending on the parameters.

I tend to like the second choice, although it feels a little regex-y. Not sure if it is worth the time to implement either. This also brings into question what exactly the matcher does when it has 10+ matching Ops with the same priority.

**Comment by ctrueden** [comment]
> I didn't want to call the Op just "copy" but rather "copy.atomicReference" - that's how it was done in the old imagej-ops (see, e.g., "copy.img", "copy.imgLabeling" etc.) and I guess that's still valid.

I disagree here. I think that an op that deep copies an object to another object should just be called `copy`. And they should all be computers, so that the type being copied into is explicit and can be overloaded. (With functions, you'd only be able to have one destination type per source type—not good.)

Not sure about the namespace. Maybe just `copy.copy`, as redundant as that seems—or no namespace, as much as I agree with @gselzer that we should minimize that. This then has the advantage that if you have an object of some arbitrary type `Foo`, you can look for a `copy` op that operates on that type, and see if such an operation exists. Without that, you'd have to either: A) guess at the op name, which is untenable; or B) do some kind of full-namespace-based matching as discussed above, which I think is wrong and unnecessary.

> I do, however, see the value in being able to compare all of the Ops in a namespace. I cannot think of any other valid scenarios outside of `copy` Ops (maybe `create` Ops too? I don't know...)

I am still not seeing the value. However, I agree that the `create` ops are the other key namespace to consider here. Especially since we are planning to use them as the foundation of the computer-to-function translation: when a computer exists but not a function, is there an op we can use to manufacture an appropriate output object? Which op would it be? A `create`! And then pass the newly created object as the computer's destination object. This would include, but not be limited to, the `copy` ops.

So then, all the creation ops would be named `create`, be functions, take as input some type `Foo`, and produce another `Foo` object as output.

Flaws in this revolutionary plan?

**Comment by MarcelWiedenmann** [comment]
Sounds good to me because it's as simple as it can get (which is always good). Also, the name `copy` (same for `create` etc.) + the signature of the Op is expressive enough to make clear what it is about, which would've been my primary argument in favor of nested namespaces a la `copy.foo` (e.g., it's pretty clear that an Op `Computer<Foo, Foo>`of name "copy" is equivalent to an Op called "copy.foo").

**Comment by MarcelWiedenmann** [comment]
Sorry for this endless list of references, I didn't realize that each commit (even if overwritten by a force-push) is kept here.

This issue should be fixed once #21 is merged.
