### ISSUE TITLE
Implement slicing functionality

### ISSUE THREAD

**Issue by ctrueden** [scijava/scijava-ops#34]
We didn't port the `slice` op yet. (Right, @gselzer?) It is very useful, and users will need it. It doesn't necessarily have to be an op—maybe a utility method in ImgLib2 core makes sense, or some helper method in imagej-ops (it's an ImgLib2-specific feature)—but it needs to be nice and easy to use from a scripting perspective.

**Comment by gselzer** [comment]
@ctrueden the op [`SliceRAI2RAI`](https://github.com/scijava/scijava-ops/blob/migrate-imagej-ops/src/main/java/net/imagej/ops/slice/SliceRAI2RAI.java) and [associated test](https://github.com/scijava/scijava-ops/blob/migrate-imagej-ops/src/test/java/net/imagej/ops/slice/SliceTest.java) have already been ported.

**Comment by ctrueden** [comment]
Ah, great! Sorry I missed that.
