### ISSUE TITLE
Add possibility for caching of Op results

### ISSUE THREAD

**Issue by Treiblesschorle** [scijava/scijava-ops#5]
There should be some way to add caching of results to the Ops, such that an Op may simply return the result for some input if it was already called with the exact same inputs by retrieving it from some cache. This may not need to be part of the ```OpEnvironment``` or directly built into the Ops as there could be a layer in between execution and ```OpEnvironment``` which wraps an Op doing some caching.

**Comment by gselzer** [comment]
I finally spent a little while thinking about this. I think that @Treiblesschorle is right in that this belongs within [`OpWrapper`s](https://github.com/scijava/incubator/blob/master/scijava/scijava-ops/src/main/java/org/scijava/ops/function/OpWrappers.java) *if* we decide that something like this is worthwhile. 

We would have to be really careful about adding this; I think that the best way to do this would be by requiring some `equals` Op (a `BiFunction<T, T, Boolean>` with functionality described by @ctrueden in scijava/scijava-ops#36) be given to the `OpWrapper`. But that would suck as `DefaultOpEnvironment.opify()` uses those wrappers.

I do not think that we can do anything simpler, as it would surely result in unintended behavior. Suppose we have a `Function<double[], double[]>`. The only efficient way I see to check whether or not you have the same inputs is by refactoring the `apply` method within `GenericTypedFunction1` to something like
```java
Map<I, O> cachedArgs;

public O apply(I in) {
  if (cachedArgs.containsKey(in)) return cachedArgs.get(in);
  return op.apply(in);
}
```
(where `containsKey` is checking that the Object itself is within the `Map`, if that is not clear).

But what if the user calls the `Function<double[], double[]` once, mutates, the input array, and then calls again? The `Map` would report that the `double[]` is already in the `Map`, the output would be wrong from the second call returning the cached output of the first call. So I do not think we can do better than `equals` ops.

Once we start talking about finding `equals` Ops to give to the wrappers, we then should discuss whether adding this form of caching will actually provide a performance boost in practice. Adding this functionality would not only require another call to the matcher, but would also enforce a linear time complexity (in terms of input size) on all Ops. Maybe this could be mitigated with a hint (see #43), or some annotation option when not desired?

If you ask me, I say we take the YAGNI approach here. I personally have never needed to call an Op twice with the exact same inputs. I also do not see any reason why you would want to (the only reason that I could think of is that you *need* two copies of the output, in which calling a `copy` op is probably faster). But I *am* open to pursuing this if someone finds a valid use case.

**Comment by ctrueden** [comment]
Current school of thought is that caching of execution can be implemented on top of the Ops framework, without needing to accommodate it within the Ops design itself. Will reopen if that ends up being wrong.
